import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { useTheme } from '../contexts/ThemeContext';
import { useLanguage } from '../i18n/LanguageContext';
import { VoiceCharacter, ScriptSection } from '../types';
import { 
  X, Play, User, Loader2, Upload, Volume2, 
  Square, Check, FileAudio, Mic, Sparkles, RotateCcw
} from 'lucide-react';
import type { Voice } from '../services/api';
import { designVoice, type VoiceDesignPreview } from '../services/api';
import { validateAudioFileSize, AudioFileTooLargeError } from '../utils/audioTrim';

interface VoicePickerModalProps {
  /** The character to assign a voice to */
  character: { name: string; description?: string; assignedVoiceId?: string; tags?: string[]; voiceDescription?: string };
  /** System voices (e.g. Gemini TTS) */
  systemVoices: Voice[];
  /** Custom voices from Voice Studio */
  customVoices: VoiceCharacter[];
  /** Currently playing voice id */
  playingVoiceId: string | null;
  /** Currently loading voice id */
  loadingVoiceId: string | null;
  /** Called when user assigns a voice */
  onAssign: (voiceId: string) => void;
  /** Called to preview/play a voice */
  onPlayVoice: (voiceId: string) => void;
  /** Called when a voice is created from uploaded file. Returns the new voice so modal can auto-assign. */
  onCreateVoice?: (name: string, description: string, file: File) => void;
  /** Called when modal closes */
  onClose: () => void;
  /** Voice IDs already assigned in the project (to prioritize in the list) */
  projectVoiceIds?: string[];
  /** Script sections for extracting character dialogue context */
  scriptSections?: ScriptSection[];
}

export function VoicePickerModal({
  character,
  systemVoices,
  customVoices,
  playingVoiceId,
  loadingVoiceId,
  onAssign,
  onPlayVoice,
  onCreateVoice,
  onClose,
  projectVoiceIds = [],
  scriptSections = [],
}: VoicePickerModalProps) {
  const { theme } = useTheme();
  const { language } = useLanguage();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [dragOver, setDragOver] = useState(false);
  
  // Upload form state
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [voiceName, setVoiceName] = useState('');
  const [voiceDescription, setVoiceDescription] = useState('');
  const [isCreating, setIsCreating] = useState(false);
  // Local audio preview for uploaded file
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [previewPlaying, setPreviewPlaying] = useState(false);
  const previewAudioRef = useRef<HTMLAudioElement | null>(null);

  // Voice design (generate) state
  const [designPrompt, setDesignPrompt] = useState('');
  const [isDesigning, setIsDesigning] = useState(false);
  const [designPreviews, setDesignPreviews] = useState<VoiceDesignPreview[]>([]);
  const [_designText, setDesignText] = useState('');
  const [designError, setDesignError] = useState<string | null>(null);
  const [playingDesignIdx, setPlayingDesignIdx] = useState<number | null>(null);
  const [selectedDesignIdx, setSelectedDesignIdx] = useState<number | null>(null);
  const [designVoiceName, setDesignVoiceName] = useState('');
  const designAudioRef = useRef<HTMLAudioElement | null>(null);

  // Extract sample dialogue lines for this character from script
  const characterLines = useMemo(() => {
    if (!character?.name || scriptSections.length === 0) return [];
    const lines: string[] = [];
    for (const section of scriptSections) {
      for (const item of section.timeline) {
        for (const line of (item.lines || [])) {
          if (line.speaker === character.name && line.line?.trim()) {
            lines.push(line.line.trim());
          }
        }
      }
      if (lines.length >= 5) break; // Enough samples
    }
    return lines.slice(0, 5);
  }, [character?.name, scriptSections]);

  // Prefill character information into create new voice forms
  useEffect(() => {
    if (!character) return;

    // Use voiceDescription as the primary AI prompt source — it's a concise English
    // TTS-oriented description generated by Gemini during script analysis
    // (e.g. "Warm deep male voice, moderate pace, studio-quality, American accent")
    if (character.voiceDescription) {
      setDesignPrompt(character.voiceDescription);
    } 

    // Prefill Upload form voice name
    setVoiceName(character.name || '');
    setVoiceDescription(character.voiceDescription || '');
    setDesignVoiceName(character.name || '');
  }, [character, language, characterLines]);

  const handleFileSelect = useCallback((file: File) => {
    try {
      validateAudioFileSize(file);
    } catch (err) {
      if (err instanceof AudioFileTooLargeError) {
        alert(language === 'zh' ? '文件大小超过 5MB 限制' : 'File exceeds the 5 MB size limit');
      }
      return;
    }
    setSelectedFile(file);
    setVoiceName(prev => prev || file.name.replace(/\.[^.]+$/, ''));
    const url = URL.createObjectURL(file);
    setPreviewUrl(url);
  }, [language]);

  const handleClearFile = useCallback(() => {
    if (previewUrl) URL.revokeObjectURL(previewUrl);
    if (previewAudioRef.current) {
      previewAudioRef.current.pause();
      previewAudioRef.current = null;
    }
    setSelectedFile(null);
    setVoiceName('');
    setVoiceDescription('');
    setPreviewUrl(null);
    setPreviewPlaying(false);
  }, [previewUrl]);

  const handlePreviewUploadedFile = useCallback(() => {
    if (!previewUrl) return;
    if (previewPlaying && previewAudioRef.current) {
      previewAudioRef.current.pause();
      previewAudioRef.current = null;
      setPreviewPlaying(false);
      return;
    }
    const audio = new Audio(previewUrl);
    audio.onended = () => { setPreviewPlaying(false); previewAudioRef.current = null; };
    audio.onerror = () => { setPreviewPlaying(false); previewAudioRef.current = null; };
    audio.play().catch(() => setPreviewPlaying(false));
    previewAudioRef.current = audio;
    setPreviewPlaying(true);
  }, [previewUrl, previewPlaying]);

  const handleCreateVoice = useCallback(async () => {
    if (!selectedFile || !voiceName.trim() || !onCreateVoice) return;
    setIsCreating(true);
    try {
      onCreateVoice(voiceName.trim(), voiceDescription.trim(), selectedFile);
      // Close modal after creation
      onClose();
    } catch {
      setIsCreating(false);
    }
  }, [selectedFile, voiceName, voiceDescription, onCreateVoice, onClose]);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const file = e.dataTransfer.files[0];
    if (file && (file.type.startsWith('audio/') || /\.(wav|mp3|ogg|flac|m4a|aac)$/i.test(file.name))) {
      handleFileSelect(file);
    }
  }, [handleFileSelect]);

  // --- Voice Design handlers ---
  const handleDesignVoice = useCallback(async () => {
    if (!designPrompt.trim() || isDesigning) return;
    setIsDesigning(true);
    setDesignError(null);
    setDesignPreviews([]);
    setDesignText('');
    setSelectedDesignIdx(null);
    setDesignVoiceName('');
    try {
      const result = await designVoice(designPrompt.trim());
      setDesignPreviews(result.previews);
      setDesignText(result.text);
    } catch (err) {
      setDesignError(err instanceof Error ? err.message : 'Failed to generate voices');
    } finally {
      setIsDesigning(false);
    }
  }, [designPrompt, isDesigning]);

  const handlePlayDesignPreview = useCallback((idx: number) => {
    // Stop current playback
    if (designAudioRef.current) {
      designAudioRef.current.pause();
      designAudioRef.current = null;
    }
    if (playingDesignIdx === idx) {
      setPlayingDesignIdx(null);
      return;
    }
    const preview = designPreviews[idx];
    if (!preview) return;
    const audio = new Audio(`data:${preview.mediaType};base64,${preview.audioBase64}`);
    audio.onended = () => { setPlayingDesignIdx(null); designAudioRef.current = null; };
    audio.onerror = () => { setPlayingDesignIdx(null); designAudioRef.current = null; };
    audio.play().catch(() => setPlayingDesignIdx(null));
    designAudioRef.current = audio;
    setPlayingDesignIdx(idx);
  }, [designPreviews, playingDesignIdx]);

  const handleSelectDesignVoice = useCallback(async () => {
    if (selectedDesignIdx === null || !onCreateVoice) return;
    const preview = designPreviews[selectedDesignIdx];
    if (!preview) return;
    setIsCreating(true);
    try {
      // Convert base64 audio to File object for onCreateVoice
      const byteChars = atob(preview.audioBase64);
      const byteNums = new Array(byteChars.length);
      for (let i = 0; i < byteChars.length; i++) {
        byteNums[i] = byteChars.charCodeAt(i);
      }
      const byteArray = new Uint8Array(byteNums);
      const blob = new Blob([byteArray], { type: preview.mediaType || 'audio/mpeg' });
      const file = new File([blob], `voice-design-${preview.generatedVoiceId}.mp3`, { type: 'audio/mpeg' });
      const name = designVoiceName.trim() || `Voice ${selectedDesignIdx + 1}`;
      onCreateVoice(name, designPrompt.trim(), file);
      onClose();
    } catch {
      setIsCreating(false);
    }
  }, [selectedDesignIdx, designPreviews, designVoiceName, designPrompt, onCreateVoice, onClose]);

  const allVoices = [
    ...systemVoices.map(v => ({
      id: v.id,
      name: v.name,
      description: language === 'zh' ? (v.descriptionZh || v.description) : v.description,
      type: 'system' as const,
    })),
    ...customVoices.map(v => ({
      id: v.id,
      name: v.name,
      description: v.description,
      type: 'custom' as const,
    })),
  ];

  const isAssigned = (voiceId: string) => character.assignedVoiceId === voiceId;

  const renderVoiceCard = (voice: { id: string; name: string; description: string; type: 'system' | 'custom' }) => {
    const assigned = isAssigned(voice.id);
    const isPlaying = playingVoiceId === voice.id;
    const isLoading = loadingVoiceId === voice.id;
    
    return (
      <div 
        key={voice.id}
        onClick={() => {
          if (assigned) {
            onPlayVoice(voice.id);
          } else {
            onAssign(voice.id);
          }
        }}
        className={`relative rounded-xl border p-4 transition-all cursor-pointer group ${
          assigned 
            ? 'border-2' 
            : 'border-t-border hover:border-t-border'
        }`}
        style={assigned ? { 
          borderColor: theme.primary,
          background: `${theme.primary}08`,
        } : { 
          background: 'var(--t-bg-card)' 
        }}
      >
        {assigned && (
          <div 
            className="absolute top-2 right-2 w-5 h-5 rounded-full flex items-center justify-center"
            style={{ background: theme.primary }}
          >
            <Check size={12} className="text-white" />
          </div>
        )}
        <div className="flex items-center gap-3">
          {/* Avatar with play overlay */}
          <div 
            className="relative w-11 h-11 rounded-full flex items-center justify-center flex-shrink-0"
            style={{ background: `${theme.primary}20` }}
            onClick={(e) => { e.stopPropagation(); onPlayVoice(voice.id); }}
          >
            {/* Default icon */}
            <span className={`transition-opacity duration-150 ${isPlaying || isLoading ? 'opacity-0' : 'group-hover:opacity-0'}`}>
              {voice.type === 'custom' ? (
                <Volume2 size={18} style={{ color: theme.primaryLight }} />
              ) : (
                <User size={18} style={{ color: theme.primaryLight }} />
              )}
            </span>
            {/* Play/Stop overlay on hover or when playing/loading */}
            <span 
              className={`absolute inset-0 flex items-center justify-center rounded-full transition-all duration-150 ${
                isPlaying || isLoading ? 'opacity-100 scale-100' : 'opacity-0 scale-90 group-hover:opacity-100 group-hover:scale-100'
              }`}
              style={{ background: isPlaying ? theme.primary : `${theme.primary}40` }}
            >
              {isLoading ? (
                <Loader2 size={16} className="animate-spin text-white" />
              ) : isPlaying ? (
                <Square size={12} className="text-white" />
              ) : (
                <Play size={16} className="ml-0.5 text-white" />
              )}
            </span>
          </div>

          {/* Info */}
          <div className="flex-1 min-w-0">
            <h4 className="text-sm font-medium text-t-text1 truncate">{voice.name}</h4>
            <p className="text-xs text-t-text3 truncate mt-0.5">{voice.description}</p>
            {voice.type === 'custom' && (
              <span className="inline-block text-[10px] px-1.5 py-0.5 rounded mt-1 bg-t-card-hover text-t-text3">
                {language === 'zh' ? '自定义' : 'Custom'}
              </span>
            )}
          </div>
        </div>
      </div>
    );
  };

  return (
    <div 
      className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-[60] p-4"
      onClick={onClose}
    >
      <div 
        className="rounded-2xl w-full max-w-3xl max-h-[80vh] overflow-hidden flex flex-col animate-slide-up border border-t-border shadow-2xl"
        style={{ background: 'var(--t-bg-base)' }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-5 py-4 flex items-center justify-between border-b border-t-border">
          <div className="flex items-center gap-3">
            <div 
              className="w-9 h-9 rounded-full flex items-center justify-center"
              style={{ background: `${theme.primary}20` }}
            >
              <User size={16} style={{ color: theme.primaryLight }} />
            </div>
            <div>
              <h3 className="text-base font-medium text-t-text1">
                {language === 'zh' ? '选择音色' : 'Choose Voice'}
              </h3>
              <div className="flex items-center gap-1.5 flex-wrap">
                <p className="text-xs text-t-text3">{character.name}</p>
                {character.tags && character.tags.length > 0 && (
                  <>
                    <span className="text-t-text3 text-[10px]">·</span>
                    {character.tags.map((tag, idx) => (
                      <span 
                        key={idx}
                        className="inline-block text-[10px] px-1.5 py-0.5 rounded-full"
                        style={{ background: `${theme.primary}15`, color: theme.primaryLight }}
                      >
                        {tag}
                      </span>
                    ))}
                  </>
                )}
              </div>
            </div>
          </div>
          <button 
            onClick={onClose} 
            className="p-1.5 rounded-lg hover:bg-t-card-hover transition-colors text-t-text3 hover:text-t-text1"
          >
            <X size={18} />
          </button>
        </div>

        {/* Content - unified layout */}
        <div className="flex-1 overflow-auto p-5">
          <div className={onCreateVoice ? 'flex gap-5' : ''}>
            {/* Left: Voice Library */}
            <div className={onCreateVoice ? 'flex-1 min-w-0' : ''}>
              {(() => {
                const projectUsedSet = new Set(projectVoiceIds);
                const projectVoices = allVoices.filter(v => projectUsedSet.has(v.id));
                const customNotInProject = allVoices.filter(v => v.type === 'custom' && !projectUsedSet.has(v.id));
                const systemNotInProject = allVoices.filter(v => v.type === 'system' && !projectUsedSet.has(v.id));

                return (
                  <div className="space-y-3">
                    {/* Voices already used in project */}
                    {projectVoices.length > 0 && (
                      <>
                        <div className="flex items-center gap-2 mb-2">
                          <span className="text-xs font-medium text-t-text3 uppercase tracking-wider">
                            {language === 'zh' ? '项目已选' : 'In Use'}
                          </span>
                          <div className="flex-1 h-px bg-t-border" />
                          <span className="text-xs text-t-text3">{projectVoices.length}</span>
                        </div>
                        {projectVoices.map(voice => renderVoiceCard(voice))}
                      </>
                    )}

                    {/* Custom voices */}
                    {customNotInProject.length > 0 && (
                      <>
                        <div className="flex items-center gap-2 mb-2 mt-4">
                          <span className="text-xs font-medium text-t-text3 uppercase tracking-wider">
                            {language === 'zh' ? '自定义音色' : 'Custom Voices'}
                          </span>
                          <div className="flex-1 h-px bg-t-border" />
                          <span className="text-xs text-t-text3">{customNotInProject.length}</span>
                        </div>
                        {customNotInProject.map(voice => renderVoiceCard(voice))}
                      </>
                    )}

                    {/* System voices */}
                    {systemNotInProject.length > 0 && (
                      <>
                        <div className="flex items-center gap-2 mb-2 mt-4">
                          <span className="text-xs font-medium text-t-text3 uppercase tracking-wider">
                            {language === 'zh' ? '系统音色' : 'System Voices'}
                          </span>
                          <div className="flex-1 h-px bg-t-border" />
                          <span className="text-xs text-t-text3">{systemNotInProject.length}</span>
                        </div>
                        {systemNotInProject.map(voice => renderVoiceCard(voice))}
                      </>
                    )}

                    {allVoices.length === 0 && (
                      <div className="text-center py-8 text-t-text3">
                        <Volume2 size={32} className="mx-auto mb-3 opacity-40" />
                        <p className="text-sm">{language === 'zh' ? '暂无可用音色' : 'No voices available'}</p>
                        <p className="text-xs mt-1">{language === 'zh' ? '请在音色工作室创建自定义音色' : 'Create custom voices in Voice Studio'}</p>
                      </div>
                    )}
                  </div>
                );
              })()}
            </div>

            {/* Right: Create options (AI Generate + Upload stacked) */}
            {onCreateVoice && (
              <div className="w-64 flex-shrink-0 space-y-3">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs font-medium text-t-text3 uppercase tracking-wider">
                    {language === 'zh' ? '或创建新音色' : 'Or Create New'}
                  </span>
                  <div className="flex-1 h-px bg-t-border" />
                </div>

                {/* AI Generate */}
                <div
                  className="rounded-xl border border-t-border p-3.5 space-y-2.5"
                  style={{ background: 'var(--t-bg-card)' }}
                >
                  <div className="flex items-center gap-2">
                    <Sparkles size={13} style={{ color: theme.primaryLight }} />
                    <span className="text-xs font-medium text-t-text2">
                      {language === 'zh' ? 'AI 生成' : 'AI Generate'}
                    </span>
                  </div>
                  <textarea
                    value={designPrompt}
                    onChange={(e) => setDesignPrompt(e.target.value)}
                    placeholder={language === 'zh'
                      ? '描述你想要的声音...'
                      : 'Describe the voice...'}
                    className="w-full px-2.5 py-2 rounded-lg border border-t-border bg-t-bg-base text-xs text-t-text1 placeholder-t-text3 focus:outline-none focus:border-t-border transition-all resize-none"
                    rows={2}
                  />
                  <button
                    onClick={handleDesignVoice}
                    disabled={!designPrompt.trim() || designPrompt.trim().length < 10 || isDesigning}
                    className="w-full flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all hover:scale-[1.02] disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
                    style={{ background: theme.primary, color: '#fff' }}
                  >
                    {isDesigning ? (
                      <Loader2 size={12} className="animate-spin" />
                    ) : (
                      <Sparkles size={12} />
                    )}
                    {isDesigning
                      ? (language === 'zh' ? '生成中...' : 'Generating...')
                      : (language === 'zh' ? '生成候选' : 'Generate')
                    }
                  </button>
                </div>

                {/* Generated voice previews */}
                {designError && (
                  <div className="rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-400">
                    {designError}
                  </div>
                )}

                {designPreviews.length > 0 && (
                  <div className="space-y-2.5">
                    <div className="flex items-center gap-2">
                      <span className="text-[10px] font-medium text-t-text3 uppercase tracking-wider">
                        {language === 'zh' ? '候选音色' : 'Candidates'}
                      </span>
                      <div className="flex-1 h-px bg-t-border" />
                      <button
                        onClick={handleDesignVoice}
                        disabled={isDesigning}
                        className="flex items-center gap-1 text-[10px] text-t-text3 hover:text-t-text2 transition-colors disabled:opacity-50"
                        title={language === 'zh' ? '重新生成' : 'Redo'}
                      >
                        <RotateCcw size={10} className={isDesigning ? 'animate-spin' : ''} />
                      </button>
                    </div>

                    <div className="space-y-1.5">
                      {designPreviews.map((preview, idx) => {
                        const isPlaying = playingDesignIdx === idx;
                        const isSelected = selectedDesignIdx === idx;
                        return (
                          <div
                            key={preview.generatedVoiceId}
                            onClick={() => setSelectedDesignIdx(idx)}
                            className={`relative flex items-center gap-2.5 rounded-lg border p-2 transition-all cursor-pointer group ${
                              isSelected ? 'border-2' : 'border-t-border hover:border-t-border'
                            }`}
                            style={isSelected ? {
                              borderColor: theme.primary,
                              background: `${theme.primary}08`,
                            } : {
                              background: 'var(--t-bg-base)'
                            }}
                          >
                            {isSelected && (
                              <div className="absolute top-1 right-1 w-3.5 h-3.5 rounded-full flex items-center justify-center" style={{ background: theme.primary }}>
                                <Check size={8} className="text-white" />
                              </div>
                            )}
                            <div
                              className="relative w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0"
                              style={{ background: `${theme.primary}20` }}
                              onClick={(e) => { e.stopPropagation(); handlePlayDesignPreview(idx); }}
                            >
                              <span className={`transition-opacity duration-150 ${isPlaying ? 'opacity-0' : 'group-hover:opacity-0'}`}>
                                <Sparkles size={12} style={{ color: theme.primaryLight }} />
                              </span>
                              <span
                                className={`absolute inset-0 flex items-center justify-center rounded-full transition-all duration-150 ${
                                  isPlaying ? 'opacity-100 scale-100' : 'opacity-0 scale-90 group-hover:opacity-100 group-hover:scale-100'
                                }`}
                                style={{ background: isPlaying ? theme.primary : `${theme.primary}40` }}
                              >
                                {isPlaying ? <Square size={8} className="text-white" /> : <Play size={10} className="ml-0.5 text-white" />}
                              </span>
                            </div>
                            <div className="min-w-0">
                              <h4 className="text-xs font-medium text-t-text1">
                                {language === 'zh' ? `候选 ${idx + 1}` : `Voice ${idx + 1}`}
                              </h4>
                              <p className="text-[10px] text-t-text3">
                                {preview.durationSecs > 0 ? `${preview.durationSecs.toFixed(1)}s` : ''} {preview.language || 'en'}
                              </p>
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    {selectedDesignIdx !== null && (
                      <div className="space-y-2 pt-1">
                        <div className="relative">
                          <Mic size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-t-text3" />
                          <input
                            type="text"
                            value={designVoiceName}
                            onChange={(e) => setDesignVoiceName(e.target.value)}
                            placeholder={language === 'zh' ? '音色名称...' : 'Voice name...'}
                            className="w-full pl-7 pr-2.5 py-2 rounded-lg border border-t-border bg-t-bg-base text-xs text-t-text1 placeholder-t-text3 focus:outline-none transition-all"
                          />
                        </div>
                        <button
                          onClick={handleSelectDesignVoice}
                          disabled={!designVoiceName.trim() || isCreating}
                          className="w-full flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all hover:scale-[1.02] disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
                          style={{ background: theme.primary, color: '#fff' }}
                        >
                          {isCreating ? <Loader2 size={12} className="animate-spin" /> : <Check size={12} />}
                          {language === 'zh' ? '创建并分配' : 'Create & Assign'}
                        </button>
                      </div>
                    )}
                  </div>
                )}

                {/* Divider */}
                <div className="flex items-center gap-2 py-0.5">
                  <div className="flex-1 h-px bg-t-border" />
                  <span className="text-[10px] text-t-text3">{language === 'zh' ? '或' : 'or'}</span>
                  <div className="flex-1 h-px bg-t-border" />
                </div>

                {/* Upload */}
                <div
                  className="rounded-xl border border-t-border p-3.5 space-y-2.5"
                  style={{ background: 'var(--t-bg-card)' }}
                >
                  <div className="flex items-center gap-2">
                    <Upload size={13} style={{ color: theme.primaryLight }} />
                    <span className="text-xs font-medium text-t-text2">
                      {language === 'zh' ? '上传音频' : 'Upload Audio'}
                    </span>
                  </div>
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="audio/*,.wav,.mp3,.ogg,.flac,.m4a,.aac"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleFileSelect(file);
                      if (fileInputRef.current) fileInputRef.current.value = '';
                    }}
                    className="hidden"
                  />

                  {!selectedFile ? (
                    <div
                      className={`border-2 border-dashed rounded-lg p-3 text-center transition-all cursor-pointer ${
                        dragOver ? '' : 'border-t-border hover:border-t-border'
                      }`}
                      style={dragOver ? { borderColor: theme.primary, background: `${theme.primary}08` } : {}}
                      onClick={() => fileInputRef.current?.click()}
                      onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
                      onDragLeave={() => setDragOver(false)}
                      onDrop={handleDrop}
                    >
                      <Upload size={18} className="mx-auto mb-1.5 text-t-text3" />
                      <p className="text-[10px] text-t-text2 font-medium">
                        {language === 'zh' ? '点击或拖拽' : 'Click or drag'}
                      </p>
                      <p className="text-[10px] text-t-text3 mt-0.5">
                        WAV, MP3, OGG, FLAC · max 5 MB
                      </p>
                    </div>
                  ) : (
                    <div className="space-y-2.5">
                      <div className="flex items-center gap-2 rounded-lg border border-t-border p-2" style={{ background: 'var(--t-bg-base)' }}>
                        <div className="w-7 h-7 rounded-md flex items-center justify-center flex-shrink-0" style={{ background: `${theme.primary}15` }}>
                          <FileAudio size={12} style={{ color: theme.primaryLight }} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-[10px] text-t-text1 font-medium truncate">{selectedFile.name}</p>
                          <p className="text-[10px] text-t-text3">{(selectedFile.size / 1024).toFixed(0)} KB</p>
                        </div>
                        <button onClick={handlePreviewUploadedFile} className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0" style={{ background: previewPlaying ? theme.primary : `${theme.primary}15` }}>
                          {previewPlaying ? <Square size={6} className="text-white" /> : <Play size={8} className="ml-0.5" style={{ color: theme.primaryLight }} />}
                        </button>
                        <button onClick={handleClearFile} className="p-0.5 rounded text-t-text3 hover:text-red-400 transition-all">
                          <X size={10} />
                        </button>
                      </div>
                      <input
                        type="text"
                        value={voiceName}
                        onChange={(e) => setVoiceName(e.target.value)}
                        placeholder={language === 'zh' ? '音色名称...' : 'Voice name...'}
                        className="w-full px-2.5 py-2 rounded-lg border border-t-border bg-t-bg-base text-xs text-t-text1 placeholder-t-text3 focus:outline-none transition-all"
                      />
                      <textarea
                        value={voiceDescription}
                        onChange={(e) => setVoiceDescription(e.target.value)}
                        placeholder={language === 'zh' ? '音色描述（可选）...' : 'Voice description (optional)...'}
                        className="w-full px-2.5 py-2 rounded-lg border border-t-border bg-t-bg-base text-xs text-t-text1 placeholder-t-text3 focus:outline-none transition-all resize-none"
                        rows={2}
                      />
                      <button
                        onClick={handleCreateVoice}
                        disabled={!voiceName.trim() || isCreating}
                        className="w-full flex items-center justify-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-all hover:scale-[1.02] disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
                        style={{ background: theme.primary, color: '#fff' }}
                      >
                        {isCreating ? <Loader2 size={12} className="animate-spin" /> : <Check size={12} />}
                        {language === 'zh' ? '创建并分配' : 'Create & Assign'}
                      </button>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 border-t border-t-border flex items-center gap-2">
          {character.assignedVoiceId ? (
            <>
              <Check size={14} style={{ color: theme.primaryLight }} />
              <span className="text-xs text-t-text3 flex-1">
                {language === 'zh' ? '当前已选择: ' : 'Currently selected: '}
                <span className="text-t-text2 font-medium">
                  {allVoices.find(v => v.id === character.assignedVoiceId)?.name || character.assignedVoiceId}
                </span>
              </span>
            </>
          ) : (
            <span className="text-xs text-t-text3 flex-1">
              {language === 'zh' ? '点击音色卡片以选择' : 'Click a voice card to select'}
            </span>
          )}
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg text-xs font-medium transition-all hover:scale-105"
            style={{ background: character.assignedVoiceId ? theme.primary : 'var(--t-bg-card-hover)', color: character.assignedVoiceId ? '#fff' : 'var(--t-text-2)' }}
          >
            {language === 'zh' ? '完成' : 'Done'}
          </button>
        </div>
      </div>
    </div>
  );
}
